const db_key = {
    groupPHOTOURL: 'pu',
    groupNAME: 'gn',
    groupTYPE: 'gtp',
    groupID: 'gid',
    groupIDfiltered: 'gidf',
    groupDESCRIPTION: 'gd',
    groupMEMBERSLIST: 'gmL',
    groupCREATEDBY: 'gcb',
    groupCREATEDON: 'gco',
    groupLATESTMESSAGETIME: 'Lt',
    groupADMINLIST: 'gaL',
    groupISTYPINGUSERID: 'git',
    groupMUTEDMEMBERS: 'gMU',

    //---   OTHER Group Chat Fileds-
    groupTYPEonlyadminmessageallowed:
        'Only Admin Messages Allowed',
    groupTYPEallusersmessageallowed:
        'Both User & Admin Messages Allowed',
    groupmsgCONTENT: 'cnt',
    groupmsgLISToptional: 'gLi',
    groupmsgTIME: 'gt',
    groupmsgSENDBY: 'gsb',
    groupmsgISDELETED: 'gisd',
    groupmsgTYPE: 'mtp',
    groupmsgISMEDIA: 'gim',
    groupmsgNOTIFICATIONtitle: 'nt',
    groupmsgNOTIFICATIONdescription: 'nd',

    //------
    groupmsgTYPEnotificationCreatedGroup: 'cg',
    groupmsgTYPEnotificationUpdatedGroupDetails: 'ugd',
    groupmsgTYPEnotificationUpdatedGroupicon: 'ugi',
    groupmsgTYPEnotificationDeletedGroupicon: 'ugdi',
    groupmsgTYPEnotificationUserSetAsAdmin: 'gusa',
    groupmsgTYPEnotificationUserRemovedAsAdmin: 'gura',
    groupmsgTYPEnotificationAddedUser: 'gau',
    groupmsgTYPEnotificationRemovedUser: 'gru',
    groupmsgTYPEnotificationUserLeft: 'rL',
    groupmsgTYPEnotificationSetToAdminOnly: 'sao',
    groupmsgTYPEnotificationSetToUsersAndAdmin: 'suo',

    groupmsgTYPEaudio: 'ga',
    groupmsgTYPEimage: 'i',
    groupmsgTYPEvideo: 'gmv',
    groupmsgTYPEdocument: 'gtd',
    groupmsgTYPElocation: 'L',
    groupmsgTYPElcontact: 'gtc',

//---
//---
//---
//---
//---
//**------  SUPPORT TICKET CHAT DATABASE KEYS - Find all ticket chat firetsore document fields here----
    ticketcosmeticID: 'csid',
    ticketID: 'tid',
    ticketcustomerID: 'cuid',
    ticketissuedby: 'ib',
    ticketStatus: 's',
    ticketTitle: 'tt',
    ticketPhotoURL: 'tpu',

    ticketDepartmentID: 'ctid',
    departmentNamestoredinList: 'tcn',
    ticketDescription: 'td',
    ticketcreatedBy: 'tcb',
    ticketidFiltered: 'tidf',
    ticketisTyingID: 'tit',
    ticketclosedby: 'cLb',
    ticketchatdeletedby: 'cdb',
    ticketMap9: 'cm',
    ticketcreatedOn: 'tco',
    ticketlatestTimestampForCustomer: 'tLt',
    ticketmediaDeletedTimestamp: 'mdt',
    tktMEMBERSactiveList: 'tmL',
    ticketadminlist: 'taL',
    transcriptsGeneratedBy: 'tg',
    rating: 'rtg',
    isreviewRequired: 'irr',
    ticketSecondaryStatus: 'tss',

//---extra
    tktLastMssgBy: 's1',
    liveAgentID: 's2',
    feedback: 's3',
    tktString4: 's4',
    tktString5: 's5',
    tktString6: 's6',
    tktString7: 's7',
    tktString8: 's8',
    tktString9: 's9',
    tktString10: 's10',
    tktString11: 's11',
    tktString12: 's12',
    tktString13: 's13',
    tktString14: 's14',
    tktString15: 's15',
    tktString16: 's16',
    tktString17: 's17',
    tktString18: 's18',

    tktNOTIFICATIONactiveList: 'L1',
    tktdepartmentNameList: 'L2',
    tktList3: 'L3',
    tktList4: 'L4',
    tktList5: 'L5',
    tktList6: 'L6',
    tktList7: 'L7',
    tktList8: 'L8',
    tktList9: 'L9',
    tktList10: 'L10',
    ticketlatestTimestampForAgents: 'i1',
    ticketStatusShort: 'i2',
    ticketClosedOn: 'i3',
    liveAgentLastonline: 'i4',
    tktInt5: 'i5',
    tktInt6: 'i6',
    tktInt7: 'i7',
    tktInt8: 'i8',
    tktInt9: 'i9',
    tktInt10: 'i10',

    tktBool1: 'b1',
    tktBool2: 'b2',
    tktBool3: 'b3',
    tktBool4: 'b4',
    tktBool5: 'b5',
    tktBool6: 'b6',
    tktBool7: 'b7',
    tktBool8: 'b8',
    tktBool9: 'b9',
    tktBool10: 'b10',
    tktBool11: 'b11',
    tktBool12: 'b12',
    tktBool13: 'b13',
    tktBool14: 'b14',
    tktBool15: 'b15',
    ticketCallInfoMap: 'm1',
    tktMap2: 'm2',
    tktMap3: 'm3',
    tktMap4: 'm4',
    tktMap5: 'm5',
    tktMap6: 'm6',
    tktMap7: 'm7',
    tktMap8: 'm8',

//---
    //  Dbkeys.groupmsgCONTENT: content,
    //       Dbkeys.groupmsgISDELETED: false,
    //       Dbkeys.groupmsgLISToptional: [],
    //       Dbkeys.groupmsgTIME: timestamp,
    //       Dbkeys.groupmsgSENDBY: widget.currentUserno,
    //       Dbkeys.groupmsgISDELETED: false,
    //       Dbkeys.groupmsgTYPE: type.index,
    //       Dbkeys.groupNAME: groupDoc[Dbkeys.groupNAME],
    //       Dbkeys.groupID: groupDoc[Dbkeys.groupNAME],
    //       Dbkeys.sendername: widget.model.currentUser![Dbkeys.nickname],
    //       Dbkeys.groupIDfiltered: groupDoc[Dbkeys.groupIDfiltered],
    //       Dbkeys.isReply: isReplyKeyboard,
    //       Dbkeys.replyToMsgDoc: replyDoc,
    //       Dbkeys.isForward: isForward
//TICKET CATEGORY FIELDS
    tktMssgCONTENT: 'tmc',
    tktMssgISDELETED: 'isD',
    tktMssgTIME: 'ti',
    tktMssgTYPE: 'ty',
    tktMsgCUSTOMERID: 'mp',
    tktMssgLISToptional: 'tLi',
    tktMssgSENDBY: 'tsb',
    tktMssgSENDFOR: 'sf',
    tktMssgISREPLY: 'ir',
    tktMssgREPLYTOMSSGDOC: 'md',
    tktMssgISFORWARD: 'if',
    tktMssgTicketName: 'tn',
    tktMssgTicketIDflitered: 'idf',
    tktMssgSENDERNAME: 'sn',

    //--extra
    tktMsgDELETEREASON: 'ts1',
    tktMsgDELETEDby: 'ts2',
    tktMsgString3: 'ts3',
    tktMsgString4: 'ts4',
    tktMsgString5: 'ts5',
    notificationActiveList: 'tL1',
    tktMsgList2: 'tL2',
    tktMsgList3: 'tL3',
    tktMsgSenderIndex: 'ti1',
    tktMsgInt2: 'ti2',
    isShowSenderNameInNotification: 'tb1',
    tktMsgBool2: 'tb2',
    tktMsgMap1: 'tm1',
    tktMsgMap2: 'tm2',

//---

//---
//TICKET CATEGORY FIELDS
    departmentTitle: 'tct',
    departmentDesc: 'tcd',
    departmentAgentsUIDList: 'tcLi',
    departmentIsShow: 'v',
    departmentCreatedby: 'u',
    departmentCreatedTime: 'tcc',
    departmentLastEditedOn: 'teo',
    departmentLogoURL: 'tul',
    departmentExtraMap1: 'tem',
    departmentExtraMap2: 'tel2',
    departmentExtraMap3: 'tel3',
    departmentExtraMap4: 'tel4',
    departmentExtraMap5: 'tel5',
    departmentExtraMap6: 'tel6',

    departmentLastEditedby: 'teb',
    departmentManagerID: 'ds1',
    deptint1: 'di1',
    deptint2: 'di2',
    deptint3: 'di3',
    deptint4: 'di4',
    deptint5: 'di5',
    deptint6: 'di6',
    deptint7: 'di7',
    deptint8: 'di8',
    deptint9: 'di9',
    deptint10: 'di10',
    deptint11: 'di11',
    deptint12: 'di12',

    deptstring2: 'ds2',
    deptstring3: 'ds3',
    deptstring4: 'ds4',
    deptstring5: 'ds5',
    deptstring6: 'ds6',
    deptstring7: 'ds7',
    deptstring8: 'ds8',
    deptstring9: 'ds9',
    deptstring10: 'ds10',
    deptstring11: 'ds11',
    deptstring12: 'ds12',
    deptstring13: 'ds13',
    deptstring14: 'ds14',
    deptstring15: 'ds15',
    deptstring16: 'ds16',
    deptstring17: 'ds17',
    deptstring18: 'ds18',

    departmentRatingsList: 'dl1',
    deptlist2: 'dl2',
    deptlist3: 'dl3',
    deptlist4: 'dl4',
    deptlist5: 'dl5',
    deptlist6: 'dl6',
    deptlist7: 'dl7',
    deptlist8: 'dl8',
    deptlist9: 'dl9',
    deptlist10: 'dl10',
    deptbool1: 'db1',
    deptbool2: 'db2',
    deptbool3: 'db3',
    deptbool4: 'db4',
    deptbool5: 'db5',
    deptbool6: 'db6',
    deptbool7: 'db7',
    deptbool8: 'db8',
    deptbool9: 'db9',
    deptbool10: 'db10',
    deptbool11: 'db11',
    deptbool12: 'db12',
    deptbool13: 'db13',
    deptbool14: 'db14',
    deptbool15: 'db15',
    deptbool16: 'db16',
    deptbool17: 'db17',
    deptbool18: 'db18',

//---
//---
//**------  DEVICE INFO  DATABASE KEYS - Find all keys of deviceinfoMAP fields here----
    deviceInfoDEVICEID: 'did',
    deviceInfoOSID: 'osid',
    deviceInfoMODEL: 'im',
    deviceInfoOSVERSION: 'osv',
    deviceInfoOS: 'ost',
    deviceInfoDEVICENAME: 'dn',
    deviceInfoMANUFACTURER: 'm',
    deviceInfoLOGINTIMESTAMP: 'dLt',
    deviceInfoISPHYSICAL: 'iph',

//---
//---
//---
//---
//---
//**------  NOTIFICATION  DOCUMENT KEYS - Find all keys of notification document fields here----
    nOTIFICATIONisunseen: 'xf4',
    nOTIFICATIONxxauthor: 'xa1',
    nOTIFICATIONxxtitle: 'xa2',
    nOTIFICATIONxxdesc: 'xa3',
    nOTIFICATIONxxaction: 'xa4',
    nOTIFICATIONxximageurl: 'xa5',
    nOTIFICATIONxxlastupdateepoch: 'xd1',
    nOTIFICATIONxxpagecomparekey: 'xa6',
    nOTIFICATIONxxpagecompareval: 'xa7',
    nOTIFICATIONxxparentid: 'xa8',
    nOTIFICATIONxxextrafield: 'xa9',
    nOTIFICATIONxxpagetype: 'xa10',
    nOTIFICATIONxxpageID: 'xa11',
    nOTIFICATIONpagetypeAllDOCSNAPLIST: 'aLd',
    nOTIFICATIONpagetypeSingleDOCinDOCSNAPLIST: 'sdd',
    nOTIFICATIONpagetypeSingleLISTinDOCSNAP: 'sLd',
    nOTIFICATIONpagecollection1: 'xa12',
    nOTIFICATIONpagedoc1: 'xa13',
    nOTIFICATIONpagecollection2: 'xa14',
    nOTIFICATIONpagedoc2: 'xa15',
    nOTIFICATIONtopic: 'xa16',

    nOTIFICATIONactionPUSH: 'PUSH',
    nOTIFICATIONactionNOPUSH: 'NOPUSH',
    topicUSERS: 'USERS',
    topicAGENTS: 'AGENTS',
    topicCUSTOMERS: 'CUSTOMERS',
    topicPARTICULARUSER: 'PUSER',
    topicADMIN: 'ADMIN',
    topicUSERSandroid: 'USERS-ANDROID',
    topicUSERSios: 'USERS-IOS',
    topicUSERSweb: 'USERS-WEB',

//---
//---
//---
//---
//---
//**------  BROADCAST CHAT  DOCUMENT KEYS - Find all keys of Broadcast Chat document fields here----
    broadcastBLACKLISTED: 'bL',
    broadcastPHOTOURL: 'bpu',
    broadcastNAME: 'bn',
    broadcastID: 'bid',
    broadcastDESCRIPTION: 'bd',
    broadcastMEMBERSLIST: 'bmL',
    broadcastCREATEDBY: 'bcb',
    broadcastCREATEDON: 'bco',
    broadcastLATESTMESSAGETIME: 'bLt',
    broadcastADMINLIST: 'baL',
    broadcastmsgCONTENT: 'cnt',
    broadcastmsgLISToptional: 'bLi',
    broadcastmsgTIME: 'bmt',
    broadcastmsgSENDBY: 'bsb',
    broadcastmsgISDELETED: 'bisd',
    broadcastmsgTYPE: 'btp',
    broadcastmsgISMEDIA: 'ism',
    broadcastmsgTYPEnotificationCreatedbroadcast: 'cb',
    broadcastmsgTYPEnotificationUpdatedbroadcastDetails:
        'ubd',
    broadcastmsgTYPEnotificationUpdatedbroadcasticon: 'ubdi',
    broadcastmsgTYPEnotificationDeletedbroadcasticon: 'udbi',
    broadcastmsgTYPEnotificationAddedUser: 'bau',
    broadcastmsgTYPEnotificationRemovedUser: 'bru',
    broadcastmsgTYPEaudio: 'audio',
    broadcastmsgTYPEimage: 'image',
    broadcastmsgTYPEvideo: 'video',
    broadcastmsgTYPEdocument: 'document',
    broadcastmsgTYPElocation: 'location',
    broadcastmsgTYPElcontact: 'contact',

    //---
//---
//---
//---
//---
//**------  STATUS  DOCUMENT KEYS - Find all keys of Status document fields here----
    statusPUBLISHERPHONE: 'sp',
    statusPUBLISHERPHONEVARIANTS: 'pv',
    statusPUBLISHEDON: 'po',
    statusEXPIRININGON: 'eo',
    statusITEMSLIST: 'iL',
    statusVIEWERLIST: 'vL',
    statusVIEWERLISTWITHTIME: 'vLt',
    statusItemID: 'sid',
    statusItemCAPTION: 'cp',
    statusItemBGCOLOR: 'bg',
    statusItemURL: 'surL',
    statusItemDURATION: 'dur',
    statusItemTYPE: 'stp',
    statustypeIMAGE: 'img',
    statustypeIMAGEwithcaption: 'imgcap',
    statustypeVIDEO: 'vdo',
    statustypeTEXT: 'txt',

    //---
//---
//---
//---
//---
//**------  FIREBASE STORAGE ERROR KEYS -Do not Change these----
    firebaseStorageNoObjectFound1: 'object-not-found',
    firebaseStorageNoObjectFound2: 'does not exist',
    firebaseStorageNoObjectFound3: 'exists',
    firebaseStorageNoObjectFound4: 'exist',
    firebaseStorageNoObjectFound5: 'Not Found',
    firebaseStorageNoObjectFound6: 'found',
    firebaseStorageNoObjectFound7: '404',
    firebaseStorageNoObjectFound8: 'not delete', //---
//---
//---
//---
//---
//**------  NOTIFICATION KEYS - Do not Change these----
    notificationStringNewTextMessage: 'ntm',
    notificationStringNewImageMessage: 'nim',
    notificationStringNewVideoMessage: 'nvm',
    notificationStringNewAudioMessage: 'nam',
    notificationStringNewContactMessage: 'ncm',
    notificationStringNewDocumentMessage: 'ndm',
    notificationStringNewLocationMessage: 'nlm',
    notificationStringNewIncomingAudioCall: 'niac',
    notificationStringNewIncomingVideoCall: 'nivc',
    notificationStringCallEnded: 'ce',
    notificationStringMissedCall: 'mc',
    notificationStringAcceptOrRejectCall: 'aorc',
    notificationStringCallRejected: 'cr',

//---
//---
//---
//---
//**------  USER  DOCUMENT KEYS - Find all keys of Customer & Agent document fields here----
    platform: 'plt',
    lastVerified: 'Lv',
    twoFactorVerification: 'tfv',
    userTypeIndex: 'utin',
    totalRepliesInTickets: 'tr',
    ratings: 'rt',
    timestampField: 'tsf',
    isTokenGenerated: 'itg',
    notificationTokens: 'nts',
    photoUrl: 'pu',
    answerTries: 'at',
    passcodeTries: 'pt',
    aboutMe: 'abm',
    email: 'e',
    password: 'pd',
    nickname: 'nck',
    messageType: 'mtp',
    from: 'fm',
    to: 'to',
    sendername: 'sname',
    hasRecipientDeleted: 'rd',
    hasSenderDeleted: 'sd',
    content: 'cnt',
    chatsWith: 'cw',
    chatStatus: 'cs',
    lastSeen: 'Ls',
    lastOnline: 'Lto',
    lastNotificationSeen: 'Lns',
    phone: 'phn',
    phoneRaw: 'phnrw',
    isSecuritySetupDone: 'issd',
    isPINsetDone: 'ipsd',
    firebaseuid: 'uid',
    id: 'id',
    answer: 'ans',
    quickReplies: 'qr',
    question: 'qus',
    passcode: 'pscd',
    hidden: 'hdn',
    locked: 'Lck',
    deleteUpto: 'du',
    timestamp: 't',
    lastAnswered: 'La',
    lastAttempt: 'Latm',
    authenticationType: 'aut',
    cachedContacts: 'cac',
    saved: 'svd',
    aliasName: 'an',
    aliasAvatar: 'av',
    publicKey: 'pbk',
    privateKey: 'pvk',
    countryCode: 'cc',
    wallpaper: 'wLp',
    crcSeperator: '&',
    currentDeviceID: 'cdid',
    lastLogin: 'LL',
    joinedOn: 'jo',
    searchKey: 'sk',
    groupsCreated: 'gc',
    blockeduserslist: 'buL',
    videoCallMade: 'vcm',
    videoCallRecieved: 'vcr',
    audioCallMade: 'acm',
    audioCallRecieved: 'acr',
    mssgSent: 'ms',
    geoMap: 'gm',
    deviceDetails: 'ddt',
    accountstatus: 'as',
    actionmessage: 'am',
    phonenumbervariants: 'pnvr',

    //---Extra fields for future scalabality
    accountcreatedby: 'us1',
    userexString1: 'us1',
    userexString2: 'us2',
    userexString3: 'us3',
    userexString4: 'us4',
    userexString5: 'us5',
    userexString6: 'us6',
    userexString7: 'us7',
    userexString8: 'us8',
    userexString9: 'us9',
    userexString10: 'us10',
    userexString11: 'us11',
    userexString12: 'us12',
    userexString13: 'us13',
    userexString14: 'us14',
    isAccountDeletedbyAdmin: 'ub1',
    userexBool2: 'ub2',
    userexBool3: 'ub3',
    userexBool5: 'ub5',
    userexBool6: 'ub6',
    userexBool7: 'ub7',
    userexBool8: 'ub8',
    userexBool11: 'ub11',
    userexBool12: 'ub12',
    rolesassigned: 'uL1',
    userexList2: 'uL2',
    userexList3: 'uL3',
    userexList4: 'uL4',
    userexList5: 'uL5',
    userexList6: 'uL6',
    userexList7: 'uL7',
    userexInt1: 'ui1',
    userexInt2: 'ui2',
    userexInt3: 'ui3',
    userexInt4: 'ui4',
    userexInt5: 'ui5',
    userexInt6: 'ui6',
    userexDouble1: 'ud1',
    userexDouble2: 'ud2',
    userexDouble3: 'ud3',
    userexDouble4: 'ud4',
    userexDouble5: 'ud5',
    userexMap2: 'um2',
    userexMap3: 'um3',
    userexMap1: 'um1',
    userexMap4: 'um4',
    userexMap5: 'um5',

//---
//---
//---
//---
//**------  USER  APP SETTINGS KEYS - Find all keys of userappsettings firestore document fields here----
    companyName: 'u1',
    companyLogoUrl: 'u2',
    agentVerificationNeeded: 'u3',
    preVerifiedAgents: 'u4',
    agentLoginEnabled: 'u5',
    agentRegistartionEnabled: 'u6',
    customerVerificationNeeded: 'u7',
    preVerifiedCustomers: 'u8',
    customerLoginEnabled: 'u9',
    customerUnderReviewAfterEditProfile: 'u10',
    isTwoFactorAuthCompulsoryforAgents: 'u11',
    isTwoFactorAuthCompulsoryforUsers: 'u12',
    agentUnderReviewAfterEditProfile: 'u13',
    agentsCanSeeCustomerStatisticsProfile: 'u14',
    secondadminCanSeeCustomerStatisticsProfile: 'u15',
    secondadminCanSeeAgentStatisticsProfile: 'u16',
    agentCanSeeAgentStatisticsProfile: 'u17',
    deleteConversationEnabledInGroup: 'u18',
    agentsCanCreateAgentsGroup: 'u19',
    secondadminCanCreateAgentsGroup: 'u20',
    isMediaSendingAllowedInGroupChat: 'u21',
    defaultMessageDeletingTimeForGroup: 'u22',
    agentCanCreateBroadcastToAgents: 'u23',
    secondadminCanCreateBroadcastToAgents: 'u24',
    agentCancreateandViewNewIndividualChat: 'u25',
    secondadminCancreateandViewNewIndividualChat: 'u26',
    defaultMessageDeletingTimeForOneToOneChat: 'u27',
    isMediaSendingAllowedInOneToOneChat: 'u28',
    deleteConversationEnabledInPersonalChat: 'u29',
    agentCanCallAgents: 'u30',
    secondadminCanCallAgents: 'u31',
    customerCanSeeAgentNameInTicketCallScreen: 'u32',
    callTypeForAgents: 'u33',
    customerCanCreateTicket: 'u34',
    agentCanCreateTicket: 'u35',
    secondadminCanCreateTicket: 'u36',
    customerCanChangeTicketStatus: 'u37',
    agentCanChangeTicketStatus: 'u38',
    secondadminCanChangeTicketStatus: 'u39',
    defaultTicketMssgsDeletingTimeAfterClosing: 'u40',
    showIsTypingInTicketChatRoom: 'u41',
    showIsCustomerOnline: 'u42',
    showIsAgentOnline: 'u43',
    isMediaSendingAllowedInTicketChatRoom: 'u44',
    isCallAssigningAllowed: 'u45',
    callTypeForTicketChatRoom: 'u46',
    customerCanRateTicket: 'u47',
    reopenTicketTillDays: 'u48',
    defaultTopicsOnLoginName: 'u50',
    departmentBasedContent: 'u51',
    departmentList: 'u52',
    autocreatesupportticket: 'u53',
    agentCanCreateInvoice: 'u54',
    secondadminCanCreateInvoice: 'u55',
    secondadminCanDeleteBroadcast: 'u56',
    showPaymentsTabInAgentAccount: 'u57',
    showPaymentsTabInCustomerAccount: 'u58',
    allowedCurrencyList: 'u59',
    isemulatorallowed: 'u60',

    //--
    isadmobshowInAndroid: 'u61',
    isadmobshowIniOS: 'u62',
    privacypolicyTYPE: 'u63',
    tncTYPE: 'u64',
    privacypolicy: 'u65',
    tnc: 'u66',
    latestappversionandroid: 'u67',
    newapplinkandroid: 'u68',
    latestappversionios: 'u69',
    newapplinkios: 'u70',
    isappunderconstructionandroid: 'u71',
    isappunderconstructionios: 'u72',
    accountapprovalmessage: 'u73',
    isshowerrorlog: 'u74',
    maintainancemessage: 'u75',
    is24hrsTimeformat: 'u76',
    isPercentProgressShowWhileUploading: 'u77',
    groupMemberslimit: 'u78',
    broadcastMemberslimit: 'u79',
    feedbackEmail: 'u80',
    isLogoutButtonShowInSettingsPage: 'u81',
    maxFileSizeAllowedInMB: 'u82',
    maxNoOfFilesInMultiSharing: 'u83',
    isCustomAppShareLink: 'u84',
    appShareMessageStringAndroid: 'u85',
    appShareMessageStringiOS: 'u86',
    maxNoOfContactsSelectForForward: 'u87',

    //---Extra fields for future scalabality
    notificationtitle: 'u88',

    exString1: 'u88',
    loginTypeUserApp: 'u88',
    notificationdesc: 'u89',
    exString2: 'u89',
    customDomainslist: 'u89',
    exString3: 'u90',
    notifcationpostedby: 'u90',
    exString4: 'u91',
    agentsLandingCustomTabURL: 'u91',
    exString5: 'u92',
    customersLandingCustomTabURL: 'u92',
    agentCustomTabLabel: 'u93',
    exString6: 'u93',
    exString7: 'u94',
    customerCustomTabLabel: 'u94',

    exString8: 'u95',
    exString9: 'u96',
    exString10: 'u97',
    exString11: 'u98',
    exString12: 'u99',
    exString13: 'u100',
    exString14: 'u101',
    exString15: 'u102',
    exString16: 'u103',
    exString17: 'u104',
    exString18: 'u186',
    exString19: 'u187',
    exString20: 'u188',
    exString21: 'u189',
    exString22: 'u190',
    exString23: 'u191',
    exString24: 'u192',
    exString25: 'u193',
    exString26: 'u194',
    exString27: 'u195',
    exString28: 'u196',
    exString29: 'u197',
    exString30: 'u198',
    exString31: 'u199',
    exString32: 'u200',
    exString33: 'u201',
    exString34: 'u202',

    exbool384: 'u105',
    exbool1123: 'u106',
    customerCanSeeAgentStatisticsProfile: 'u107',
    departmentmanagerCancreateandViewNewIndividualChat:
        'u108',
    departmentmanagerCanViewGlobalDepartments: 'u109',
    exBool6: 'u110',
    autoJoinNewAgentsToDefaultList: 'u110',
    customerRegistationEnabled: 'u110',
    secondadminCanViewGloabalBroadcast: 'u111',
    exBool7: 'u111',
    isCustomDomainsOnly: 'u111',
    exBool8: 'u112',
    departmentManagerCanCreateAgentsGroup: 'u112',
    exBool9: 'u113',
    secondadminCanViewAllGlobalChats: 'u113',
    departmentmanagerCanDeleteBroadcast: 'u203',
    departmentmanagerCanViewGloabalBroadcast: 'u204',
    agentCanViewAllTicketGlobally: 'u205',
    departmentmanagerCanViewAllTicketGlobally: 'u206',
    departmentManagerCanViewDepartmentGroups: 'u207',
    secondadminCanViewDepartmentGroups: 'u208',
    secondadminCanViewAllGlobalgroups: 'u209',
    agentsCanViewGlobalDepartments: 'u210',
    departmentmanagerCanDeleteDepartment: 'u211',
    departmentManagerCanCreateDepartmentGlobally: 'u212',
    exBool20: 'u213',
    agentCanDeleteBroadcast: 'u214',
    departmentmanagercanseeagentnameandphoto: 'u215',
    departmentmanagercanseecustomernameandphoto: 'u216',
    agentcanseecustomernameandphoto: 'u217',
    secondadmincanseecustomernameandphoto: 'u218',
    agentsCanSeeOwnDepartmentACustomer: 'u248',
    agentCanSeeCustomerContactInfo: 'u249',
    secondadminCanSeeCustomerContactInfo: 'u250',
    departmentmanagerCanSeeCustomerStatisticsProfile: 'u251',
    departmentmanagerCanSeeCustomerContactinfo: 'u252',
    exbool244: 'u253',
    secondadminCanSeeCustomerContactinfo: 'u254',
    departmentmanagerCanSeeAgentStatisticsProfile: 'u256',
    secondadminCanSeeAgentContactinfo: 'u257',
    departmentmanagerCanSeeAgentContactinfo: 'u258',
    agentCanSeeAgentContactinfo: 'u259',
    customerCanSeeAgentContactinfo: 'u260',
    departmentManagerCanViewAllGlobalgroups: 'u261',
    agentsCanSeeOwnDepartmentAgents: 'u261',
    departmentManagerCanViewAllGlobalChats: 'u262',
    departmentmanagerCanViewAllAgentsGlobally: 'u263',
    agentsCanViewAllAgentsGlobally: 'u264',
    agentsCanViewAllCustomerGlobally: 'u265',
    departmentmanagerCanViewAllCustomerGlobally: 'u266',
    customerCanDialCallsInTicketChatroom: 'u267',
    agentCanReopenTicket: 'u268',
    customerCanReopenTicket: 'u269',
    customerCanCloseTicket: 'u270',
    agentCanScheduleCalls: 'u271',
    customerCanViewAgentsListJoinedTicket: 'u272',
    secondadmincanseeagentnameandphoto: 'u273',
    agentcanseeagentnameandphoto: 'u274',
    customercanseeagentnameandphoto: 'u275',
    departmentmanagerCanCreateBroadcastToAgents: 'u276',
    secondadminCanViewGlobalDepartments: 'u277',
    customerCanViewGlobalDepartments: 'u278',
    secondAdminCanviewDepartmentStatistics: 'u279',
    departmentmanagerCanviewDepartmentStatistics: 'u280',
    secondadminCanDeleteDepartment: 'u281',
    secondAdminCanEditDepartment: 'u282',
    departmentManagerCanEditAddAgentstodepartment: 'u283',
    secondAdminCanCreateDepartmentGlobally: 'u284',
    departmentManagerCanCreateTicket: 'u285',
    secondadminCanViewAllTicketGlobally: 'u286',
    agentcanChatWithCustomerInTicket: 'u287',
    secondadminCanChatWithCustomerInTicket: 'u288',
    departmentmanagerCanChatWithCustomerInTicket: 'u289',
    departmentmanagerCanChangeTicketStatus: 'u290',
    departmentmanagerCanViewAgentsListJoinedTicket: 'u291',
    secondadminCanViewAgentsListJoinedTicket: 'u292',
    agentCanViewAgentsListJoinedTicket: 'u293',
    secondadminCanScheduleCalls: 'u294',
    departmentManagerCanScheduleCalls: 'u295',
    agentCanCloseTicket: 'u296',
    departmentmanagerCanCloseTicket: 'u297',
    secondAdminCanCloseTicket: 'u298',
    departmentManagerCanReopenTicket: 'u299',
    secondadminCanReopenTicket: 'u300',
    viewowntickets: 'u301',
    secondadminCanViewAllCustomerGlobally: 'u302',
    viewOwnCustomerWithinDepartments: 'u303',
    viewOwnAgentsWithinDepartments: 'u304',
    secondadminCanViewAllAgentsGlobally: 'u305',
    departmentManagerCanSeeOwnDepartmentCustomers: 'u306',
    departmentManagerCanSeeOwnDepartmentAgents: 'u307',
    isShowHeaderAgentsTab: 'u308',
    isShowHeaderCustomersTab: 'u309',
    isShowFooterAgentsTab: 'u310',
    isShowFooterCustomersTab: 'u311',
    exBool89: 'u312',
    exBool90: 'u313',

    isPhoneAuthenticationMandatory: 'u114',
    isEmailLoginEnabled: 'u115',
    exBool4: 'u116',
    exbool453: 'u117',
    isFbLoginEnabled: 'u118',
    isGoogleLoginEnabled: 'u119',
    demoIDsList: 'u120',
    exList1: 'u120',
    exList2: 'u121',
    exList3: 'u122',
    exList4: 'u123',
    exList5: 'u124',
    exList6: 'u125',
    exList7: 'u141',
    exList8: 'u142',
    exList9: 'u143',
    exList10: 'u144',
    exList11: 'u145',
    exList12: 'u146',

    exInt1: 'u126',
    personalcalltypeagents: 'u126',
    exInt2: 'u127',
    notificationtime: 'u127',
    customerTabIndexPosition: 'u128',
    agentTabIndexPosition: 'u129',
    exInt5: 'u130',
    exInt6: 'u147',
    exInt7: 'u148',
    exInt8: 'u149',
    exInt9: 'u150',
    exInt10: 'u151',
    exInt11: 'u152',
    exInt12: 'u153',
    exInt13: 'u154',
    exInt14: 'u155',
    exInt15: 'u156',
    exInt16: 'u157',
    exInt17: 'u158',
    exInt18: 'u169',
    exInt19: 'u170',
    exInt20: 'u171',
    exInt21: 'u172',
    exInt22: 'u173',
    exInt23: 'u174',
    exInt24: 'u175',
    exInt25: 'u176',
    exInt26: 'u219',
    exInt27: 'u220',
    exInt28: 'u221',
    exInt29: 'u222',
    exInt30: 'u223',
    exInt31: 'u224',
    exInt32: 'u225',
    exInt33: 'u226',
    exInt34: 'u227',
    exInt35: 'u228',
    exInt36: 'u229',
    exInt37: 'u230',
    exInt38: 'u231',
    exInt39: 'u232',
    exInt40: 'u233',
    exInt41: 'u234',
    exInt42: 'u235',
    exInt43: 'u236',
    exInt44: 'u237',
    exInt45: 'u238',
    exInt46: 'u239',
    exInt47: 'u240',
    exInt48: 'u241',
    exInt49: 'u242',
    exInt50: 'u243',
    exInt51: 'u244',
    exInt52: 'u245',
    exInt53: 'u246',
    exInt54: 'u247',

    exDouble1: 'u131',
    exDouble2: 'u132',
    exDouble3: 'u133',
    exDouble4: 'u134',
    exDouble5: 'u135',
    exDouble6: 'u177',
    exDouble7: 'u178',
    exDouble8: 'u179',
    exDouble9: 'u180',
    exDouble10: 'u181',

    exBool100: 'u351',
    exBool101: 'u352',
    exBool102: 'u353',
    exBool103: 'u354',
    exBool104: 'u355',
    exBool105: 'u356',
    exBool106: 'u357',
    exBool107: 'u358',
    exBool108: 'u359',
    exBool109: 'u360',
    exBool110: 'u361',
    exBool111: 'u362',
    exBool112: 'u363',
    exBool113: 'u364',
    exBool114: 'u365',
    exBool115: 'u366',
    exBool116: 'u367',
    exBool117: 'u368',
    exBool118: 'u369',
    exBool119: 'u370',
    exBool120: 'u371',
    exBool121: 'u372',
    exBool122: 'u373',
    exBool123: 'u374',
    exBool124: 'u375',
    exBool125: 'u376',
    exBool126: 'u377',
    exBool127: 'u378',
    exBool128: 'u379',
    exBool129: 'u380',
    exBool130: 'u381',
    exBool131: 'u382',
    exBool132: 'u383',
    exBool133: 'u384',
    exBool134: 'u385',
    exBool135: 'u386',
    exBool136: 'u387',
    exBool137: 'u388',
    exBool138: 'u389',
    exBool139: 'u390',
    exBool140: 'u391',
    exBool141: 'u392',
    exBool142: 'u393',
    exBool143: 'u394',
    exBool144: 'u395',
    exBool145: 'u396',
    exBool146: 'u397',
    exBool147: 'u398',
    exBool148: 'u399',
    exBool149: 'u400',
    exBool150: 'u401',
    exBool151: 'u402',
    exBool152: 'u403',
    exBool153: 'u404',
    exBool154: 'u405',
    exBool156: 'u406',
    exBool157: 'u407',
    exBool158: 'u408',
    exBool159: 'u409',
    exBool160: 'u410',
    exBool161: 'u411',
    exBool162: 'u412',
    exBool163: 'u413',
    exBool164: 'u414',
    exBool165: 'u415',
    exBool166: 'u416',
    exBool167: 'u417',
    exBool168: 'u418',
    exBool169: 'u419',
    exBool170: 'u420',
    exBool171: 'u421',
    exBool172: 'u422',
    exBool173: 'u423',
    exBool174: 'u424',
    exBool175: 'u425',
    exBool176: 'u426',
    exBool177: 'u427',
    exBool178: 'u428',
    exBool179: 'u429',
    exBool180: 'u430',
    exBool181: 'u431',
    exBool182: 'u432',
    exBool183: 'u434',
    exBool184: 'u435',
    exBool185: 'u436',
    exBool186: 'u437',
    exBool187: 'u438',
    exBool188: 'u439',
    exBool189: 'u440',
    exBool190: 'u441',
    exBool191: 'u442',
    exBool192: 'u443',
    exBool193: 'u444',
    exBool194: 'u445',
    exBool195: 'u446',
    exBool196: 'u447',
    exBool197: 'u448',
    exBool198: 'u449',
    exBool199: 'u450',
    exBool200: 'u451',

    exMap1: 'u136',
    exMap2: 'u137',
    exMap3: 'u138',
    exMap4: 'u139',
    exMap5: 'u140',
    exMap6: 'u182',
    exMap7: 'u183',
    exMap8: 'u184',
    exMap9: 'u185',

    //---- temporay
    istextmessageallowed: 't1',
    iscallsallowed: 't2',
    ismediamessageallowed: 't3',
    isadmobshow: 't4',
    isblocknewlogins: 't5',
    isaccountapprovalbyadminneeded: 't6',
    isAllowCreatingGroups: 't7',
    isAllowCreatingBroadcasts: 't8',
    isAllowCreatingStatus: 't9',
    statusDeleteAfterInHours: 't10',
    updateV7done: 't11',

    //---
//---
//---
//---
//**------  DATA COUNTS - Find all keys of datacounts firestore document fields here----
    totalapprovedagents: 'totalapprovedagents',
    totalapprovedcustomers: 'totalapprovedcustomers',
    totalblockedagents: 'totalblockedagents',
    totalblockedcustomers: 'totalblockedcustomers',
    totalpendingagents: 'totalpendingagents',
    totalpendingcustomers: 'totalpendingcustomers',
    latestappversionweb: 'latestappversionweb',
    totalvisitsANDROID: 'totalvisitsANDROID',
    totalvisitsIOS: 'totalvisitsIOS',
    totalusers: 'totalusers',

//---
//---
//---
//---
//---
//---
//---
//**------  All Additional extras---

    //---

    issetupdone: 'xhxaxftaft',
    isupdatemandatory: 'isupdatemandatory',
    isappunderconstructionweb: 'isappunderconstructionweb',

    alloweddebuggersUID: 'alloweddebuggersUID',
    isblockedCOD: 'isblockedCOD',
    newapplinkweb: 'newapplinkweb',
    url: 'url',
    file: 'file',
    usersidesetupdone: 'usersidesetupdone',
    adminsidesetupdone: 'adminsidesetupdone',

//-added in update-
    isCallFeatureTotallyHide: 'isCallFeatureTotallyHide',

    // Status--------
    sTATUSblocked: 'blocked',
    sTATUSallowed: 'allowed',
    sTATUSpending: 'pending',

    //---

    //---
    docid: 'docid',
    lastMessageTime: 'lm',
    list: 'list',
    lastupdatedepoch: 'lue',

    //--
    //  audiocallsmade : 'audiocallsmade',
    //  videocallsmade : 'videocallsmade',
    mediamessagessent: 'mediamessagessent',
    totalopentickets: 'dd1',
    totalclosedtickets: 'dd2',
    audiocallsmade: 'dd3',
    videocallsmade: 'dd4',
    totalAgentGroups: 'dd10',
    totalAgentChats: 'dd11',

    //----All App Constants ----
//---
//---
//---
//---
    liveEventListenForCustomer: "liveEventListenForCustomer",
    liveEventListenForAgent: "liveEventListenForAgent",

    //-
    isbroadcast: 'isbroadcast',
    broadcastLocations: 'broadcastLocations',

    //---
    notificationStringsMap: 'notificationsMap',
    kycMap: 'kmp',
    isNotificationStringsMulitilanguageEnabled:
        'isMultiLangNotifEnabled',
    triesThreshold: 3,
    timeBase: 2,
    //--
    datatypeAGENTS: 'AGENTS',
    datatypeCUSTOMER: 'CUSTOMER',
    datatypeGROUPCHATMSGS: 'groupchatMSGS',
    datatypeBROADCASTCMSGS: 'broadcastMSGS',
    datatypeTICKETMSSGS: 'ticketMSGS',
    isReply: 'isReply',
    replyToMsgDoc: 'replyToMsgDoc',
    isForward: 'isForward',
    //--
    userLoginType: 'logintype',
    secondadminID: 'sa1',
    managerPhoneSetOperations: 'mps',

    //  colortype : 'colorType',

    dynamicPhoneORID: 'dnm',

    //----ROLES ASSIGNED-----
    roleCANCREATETICKET: 'rwk',
    roleCANCHANGETICKETSTATUS: 'rpe',
    roleCANCLOSETICKET: 'r1w',
    roleCANSEECUSTOMERBASICDETAILS: 'rp3',
    roleCANSEECUSTOMERCONTACTDETAILS: 'r5p',
    roleCANSEEALLAGENTSLIST: 'r2a',
    roleCANCHATWITHAGENT: 'r67',
    roleCANSEEAGENTBASICDEATILS: 'rs2',
    roleCANSEEAGENTCONTACTDEATILS: 'r3d',
    roleCANCREATEGROUPCHAT: 'r0d',
    roleCANSEEALLGROUPMEMBERS: 'r5k',
    roleCANCREATESENTBROADCAST: 'r9p',
    roleCANADDREMOVESTAFFSTOTICKET: 'r85',
    roleCANSEEALLTICKETS: 'r2h',
    roleCANSEEONLYASSIGNEDTICKETS: 'r4h',
    roleCANCREATEDELETETICKETDEPARTMENTS: 'rh8',
    roleCANCREATESEESTORY: 'r5l',
    roleCANMANAGETODOLIST: 'rl1',
    roleCANSENDNOTIFICATIONTOALLAGENTS: 'rxs',
    roleCANSENDNOTIFICATIONTOALLCUSTOMERS: 'rm3',
    roleCANSEEALLAGENTSINTHESAMTICKET: 'rpq',
    roleCANSEEIFCUSTOMERISONLINEINTICKET: 'r9z',
    roleCANSEEIFAGENTISONLINEINTICKET: 'r7m',
    roleCANUSESECRETCHATINTICKET: 'r1m',
    roleCANASSIGNAAGENTFORCALL: 'r2k',
    roleCANSEEALLAGENTSCALLLOG: 'r19',
    roleCANSEEALLINVOICESANDCREATE: 'r8a',
    roleCANSEEONLYLINKEDINVOICES: 'r12',
    roleCANSEEALLGROUPCONVERSATIONANDBLOCKIFNEEDED: 'r1v',

    rgstFULLNAME: 'n',
    rgstSHORTNAME: 's',
    rgstPHOTOURL: 'd',
    rgstPHONE: 'p',
    rgstUSERTYPE: 'u',
    rgstUSERID: 'i',
    rgstEXTRA1: 'x',
    rgstEXTRA2: 'k',
    rgstEMAIL: 'e',
    rgstEXTRAMAP: 'mp',

    // PRIMARY ---------
    countrywisedata: 'countrywisedata',
    setup: 'setup',
    automaticChecks: 'automaticChecks',
    users: 'users',
    staffs: 'staffs',
    partners: 'partners',
    admin: 'admin',
    userapp: 'userapp',
    staffapp: 'staffapp',
    partnerapp: 'partnerapp',

    latestappversionwindows: 'latestappversionwindows',
    latestappversionmac: 'latestappversionmac',
    appsettings: 'appsettings',

//-----Admin Key------

    adminphotourl: 'pa4',
    adminpin: 'pa3',
    admintoken: 'pa2',
    adminfullname: 'pa1',
    adminloginhistory: 'pb2',
    admindeviceid: 'pa5',
    admindeviceslist: 'pb1',
    adminlogineventsTIME: 'tm',
    adminlogineventsTITLE: 'ttl',
    adminlogineventsDESC: 'dsc',
    adminlogineventsLOCATIONGEOCORD: 'tloc',
    adminlogineventsTITLEcredchange: 'credchng',

    pROVIDERgoogle: 'google.com',
    pROVIDEfacebook: 'facebook.com',
    pROVIDEgooglefacebook: 'google.comfacebook.com',
    pROVIDEfacebookgoogle: 'facebook.comgoogle.com',

    // //---
    //  uSERproviderid : 'providerid',
    //  uSERrole : 'role',
    //  uSERtimezoneinminutes : 'timezoneinminutes',
    //  uSERisverfiedaccount : 'isverfiedaccount',
    //  uSERfullname : 'nickname',
    //  uSERemail : 'email',
    //  uSERphone : 'phone',
    //  uSERphonecountrycodenumber : 'phonecountrycodenumber',
    //  uSERphonecountrycodename : 'phonecountrycodename',
    //  uSERphotourl : 'photoUrl',
    //  uSERsearchkey : 'searchkey',
    //  uSERcountrycode : 'countryCode',
    //  uSERphonesecondary : 'phonesecondary',

    //  uSERuid : 'uid',
    //  uSERlastlogin : 'lastlogin',

    //  uSERlastseen : 'lastSeen',
    //  uSERaccountcreatedon : 'accountcreatedon',
    //  uSERandroidnotificationtoken : 'androidnotificationtoken',
    //  uSERactionmessage : 'actionmessage',
    //  uSERaccountstatus : 'accountstatus',
    //  uSERnotificationtokenlist : 'notificationtokenlist',
    //  uSERdevicelist : 'deviceDetails',
    // //--

    //-
    hISTORYtitle: 'title',
    hISTORYdesc: 'desc',
    hISTORYtimestamp: 'timestamp',
    hISTORYcreatedby: 'createdby',
    hISTORYcreatortype: 'creatortype',
    hISTORYlevel: 'level',

    //-----
    errorREASONissinglgeloginonly: 'issingleloginonly',
    errorREASONdeviceisemulator: 'demulator',
    errorREASONuserblocked: 'userblocked',
    errorREASONuserpending: 'userpending',
    errorREASONerror: 'error',
    errorREASONundermaintainance: 'undermaintainance',
    errorREASONupdaterequired: 'updaterequired',

    sTATUSverified: 'verified',
    sTATUSdone: 'done',

    isphonenumbermandatorywhilelogin:
        'isphonenumbermandatorywhilelogin',
    isphonenumberpreffered: 'isphonenumberpreffered',

    isgeolocationprefered: 'isgeolocationprefered',
    isgeolocationmandatory: 'isgeolocationmandatory',
    isCollectDeviceInfoAndSavetoDatabase:
        'iscollectdeviceinfo',
    isOnlySingleDeviceLoginAllowed:
        'isOnlySingleDeviceallow',
    islocationeditallowed: 'isloceditalwd',

    newapplinkwindows: 'newapplinkwindows',
    newapplinkmac: 'newapplinkmac',

    //  newstaffapplink : 'newstaffapplink',
    //  newpartnerapplink : 'newpartnerapplink',
    //  newadminapplink : 'newadminapplink',

    isappunderconstructionmac: 'isappunderconstructionmac',
    isappunderconstructionwindows:
        'isappunderconstructionwindows',
    isMuted: 'iMu',
    tempcontent: 'tdc',
    deletedType: 'dlb',
    deletedReason: 'dlrs',

    //  totalapprovedusers : 'totalapprovedusers',
    //  totalblockedusers : 'totalblockedusers',
    //  totalpendingusers : 'totalpendingusers',
    //  totalapprovedstaffs : 'totalapprovedstaffs',
    //  totalblockedstaffs : 'totalblockedstaffs',
    //  totalpendingstaffs : 'totalpendingstaffs',
    //  totalapprovedpartners : 'totalapprovedpartners',
    //  totalblockedpartners : 'totalblockedpartners',
    //  totalpendingpartners : 'totalpendingpartners',

    alertISSOLVED: 'ais',
    alertTITLE: 'at',
    alertDESC: 'ad',
    alertUSERSTYPE: 'aut',
    alertUSERSUID: 'auid',
    alertTIMESTAMP: 'ats',

    //------------

    pageIDAllNotifications: 'AllNotifications',

    sharedPREFisLocationSkipped: 'isLocationSkipped',
    sharedPREFisUpdateappSkipped: 'isUpdateappSkipped',
    sharedPREFisPhoneSkipped: 'isPhoneSkipped',

    //---
    sortbyBLOCKED: 'All Blocked',
    sortbyPENDING: 'All Pending',
    sortbyAPPROVED: 'All Approved',
    sortbyALLUSERS: 'All Users',
    sortbyUSERSONLINE: 'Online Users',

    //--

    dataTypeCUSTOMERS: 'dataTypeCUSTOMERS',
    dataTypeAGENTS: 'dataTypeAGENTS',
    dataTypePARTNERS: 'dataTypePARTNERS',
    dataTypeNOTIFICATIONS: 'dataTypeNOTIFICATIONS',
    dataTypeHISTORY: 'dataTypeHISTORY',
    dataTypeCALLHISTORY: 'dataTypeCALLHISTORY',
    dataTypeREPORTS: 'dataTypeREPORTS',
    dataTypeMESSAGES: 'dataTypeMESSAGES',

    ticketCallId: 'tA',
    ticketCallAssignedBy: 'tAs',
    ticketCallAssignedTime: 'tAT',

    setupNotdoneyet: 'pf2',

}

module.exports = {
    db_key:db_key
};
